const courses = [
  "Business",
  "Health Sciences",
  "Economics",
  "Social Service",
  "Accounting",
  "Environment",
  "Finance",
  "Geographic",
  "Computer Science",
  "General",
  "Engineering",
  "Hospitality",
  "Marketing",
  "Trading",
  "Technology",
  "Creative Arts",
  "Education",
  "Fine Arts",
  "Phyisics",
  "Science",
  "physiology",
  "24",
  "2",
  "3",
  "Biology",
  "Bio technology",
  "Chemical",
  "Earth Science",
  "Neurology",
  "Child and Youth",
  "Acting",
  "Political Science",
  "Social Science",
  "Scocial Science",
  "Administration",
  "Civil Engeenering",
  "Mechenical",
  "Electrical",
  "Technician",
  "Information Technology",
  "Dental",
  "Nursing",
  "GNM",
  "Gernal medical",
  "Coustruction",
  "Technical",
  "Arts",
  "Law",
  "Communication",
  "Management",
  "Art & Design",
  "Game Develpoment",
  "Design",
  "Office Assistant",
  "Journalism",
  "",
  "Computer",
  "Electronic",
  "Digital Media",
  "Mental Health",
  "Digital media",
  "Automotive",
  "Aviation",
  "Community Services",
  "Engineering Technology",
  "Health",
  "Hospitality & Tourism",
  "Media Arts",
  "Natural Resources",
  "Preparatory Studies",
  "Skilled Trades",
  "Social Arts",
  "Network Systems",
  "Agriculture",
  "Home Science",
  "Criminal Justice",
  "Information System",
  "Science and Horticulture",
  "Human Resource",
  "Data analaysing",
  "Social devlopment",
  "Media",
  "Fashion Design",
  "Hospitality And tourism",
  "Film Arts",
  "Graphic Designing",
  "Interior Design",
  "History",
  "Humanities",
  "Air Craft",
  "Aquaculture",
  "Carpentary",
  "Photography",
  "Web Designing",
  "Security Systems",
  "Global mngt",
  "Tourism",
  "Paramedic",
  "Chemical Engineering",
  "Equipment Engineering",
  "Wildlife",
  "Wildlife & Agriculture",
  "Industrial",
  "Animation",
  "Architectre",
  "Laboratory",
  "Sociology",
  "Applied Human Nutrition",
  "Arts and Science",
  "23",
  "Hospitality and Tourism",
  "Liberal Arts",
  "Global Studies",
  "Gernal Studies",
  "Medical Health",
  "Classics",
  "English",
  "Forestry",
  "Maths",
  "Engineering & Applied Science",
  "Arts (Humanities & Social Sciences)",
  "EDUCATION",
  "Media, Art, & Performance",
  "Kinesiology & Health Studies",
  "SCIENCE",
  "Mathematics",
  "Actuarial",
  "Anthropology",
  "Interpreting",
  "Bussiness",
  "Health Science",
  "Bio Science",
  "Chemical Science",
  "Social",
  "Film & Arts",
  "Human Services",
  "International Management",
  "Architecture",
  "Designing",
  "Criminology",
  "Corporate Innovation",
  "Enviromental Science",
  "Forensic",
  "Physics",
  "Public Relations",
  "Interior Science",
  "Civil Engg",
  "Mechanical Science",
  "Graphic Design",
  "Literature",
  "Geographic Science",
  "Political Scence",
  "Psychology",
  "Music",
  "Sports",
  "Construction",
  "Relations",
  "Digital Science",
  "Applied Science",
  "Advertising",
  "Physical Education",
  "Liberal Studies",
  "Global Bussiness",
  "Social media",
  "Physiology",
  "Social Studies",
  "Manufacturing",
  "Biochemistry",
  "Medical laboratry",
  "Cookery",
  "Security Specialist",
  "Design Technology",
  "veterinary science",
  "Cultural Arts",
  "Logistics",
  "Development",
  "Hospitality Management",
  "Kinesiology",
  "Dynamic",
  "Geological",
  "Zoology",
  "Sales Management",
  "Pharmacy",
  "BioChemistry",
  "Fitness",
  "legal Studies",
  "Gernal Arts",
  "Judicial",
  "Data Security Analytics",
  "Food Science",
  "Hospitality management",
  "Botany",
  "Community",
  "Medicine",
  "Horticulture",
  "Family Studies",
  "Nutritional",
  "Supply Chain Mgmt",
  "Clothing",
  "Artificial Engineering",
  "Software Engineering",
  "Network Engineering",
  "Theological",
  "Leadership",
  "Bio Technology",
  "Bio Engineering",
  "Digital Arts",
  "Data  Science",
  "Mechatronic",
  "Audio Engineering",
  "Cosmetology",
  "Culinary Arts",
  "Oil & Gas",
  "Viticulture",
  "Cyber Security",
  "Theatre",
  "Operation",
  "Pre Business",
  "Adminstration",
  "Engineering and Technology",
  "BionFormatics",
  "Biology Science",
  "Cartography",
  "Bachelore of Arts",
  "Bsc Agriculture",
  "Bachelore of Digital Media",
  "Bachelore of Commerce",
  "Civil",
  "NURSING",
  "Medical Science",
  "Bachelore in Veterinary",
  "Bachelore in Skill Management",
  "Mechanical",
  "Bachelore in Fashion  Design",
  "Medical in Nursury Production",
  "Bachelore in Cookery",
  "Bachelore in Wine Making",
  "Bachelore of Health Science",
  "B.ED",
  "Culinary, Hospitality and Baking",
  "Digital Technologies",
  "Natural Sciences",
  "Early Childhood Teaching",
  "veternairy",
  "Arts & Design",
  "Computing",
  "Cyber",
  "Networking",
  "Operations",
  "Project Management",
  "Enviromental",
  "interior Design",
  "Wine Making",
  "Banking",
  "judicial",
  "Electrical Engineering",
  "Information and Communications",
  "Legal Studies",
  "Data Networking",
  "H.R Management",
  "Health Care",
  "Digital Technology",
  "Theraphy",
  "Massage",
  "Computers",
];

const highEducation = [
  { label: "Grade 12/High School", programLevel: "1", value: "secondary" },
  {
    label: "1-Year Post-Secondary Certificate",
    programLevel: "1",
    value: "certificate",
  },
  {
    label: "2-Year Undergraduate Diploma",
    programLevel: "1",
    value: "diploma",
  },
  {
    label: "3-Year Undergraduate Advanced Diploma",
    programLevel: "1",
    value: "advance_diploma",
  },
  {
    label: "3-Year Bachelor's Degree",
    programLevel: "2",
    value: "3_year_bachlor",
  },
  {
    label: "4-Year Bachelor's Degree",
    programLevel: "2",
    value: "4_year_bachlor",
  },
  {
    label: "Postgraduate Certificate/Diploma",
    programLevel: "2",
    value: "postgraduate_diploma",
  },
  { label: "Master's Degree", programLevel: "2", value: "master" },
  {
    label: "Doctoral Degree (Phd, M.D., ...)",
    programLevel: "2",
    value: "doctrate",
  },
];

const Stream_ids = ["3", "23", "2", "24", "0", "25"];
