const mongoose = require("mongoose");

const AgentInfoSchema = mongoose.Schema(
  {
    company_name: { type: String },
    email: { type: String },
    website: { type: String },
    facebook: { type: String },
    instagram: { type: String },
    twitter: { type: String },
    linkedin: { type: String },
    principle_country: { type: String },
    legal_first_name: { type: String },
    legal_last_name: { type: String },
    streat_address: { type: String },
    city: { type: String },
    state: { type: String },
    country: { type: String },
    postal_code: { type: String },
    phone: { type: String },
    cellphone: { type: String },
    skype_id: { type: String },
    whatsapp_id: { type: String },
    referred_name: { type: String },
    recruiting_student: { type: String },
    services_provide: { type: String },
    school_represented: [],
    institutions_responding: { type: String },
    group_orginization: { type: String },
    recruit_from: { type: String },
    many_student: { type: String },
    marketing_methods: [],
    describe_marketing_methods: { type: String },
    average_service_fee: { type: String },
    refer_student: { type: String },
    additional_comments: { type: String },
    reference_name: { type: String },
    reference_institution: { type: String },
    reference_business: { type: String },
    reference_phone: { type: String },
    reference_website: { type: String },
    // company_logo: { type: String },
    // business_certificate: { type: String },
    commission: { type: String },
    approved: { type: String },
    agent_token: { type: String },
    delete_status: { type: String },
    password: { type: String },
  },
  {
    collection: "AgentInfo",
    timestamps: true,
  }
);

module.exports = mongoose.model("AgentInfo", AgentInfoSchema);
